name: verdevivo_ia_prototype
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0' # Ajuste conforme sua versão do Dart/Flutter

dependencies:
  flutter:
    sdk: flutter
  
  # Pacotes que já tínhamos
  image_picker: ^1.0.7 # ou mais recente
  share_plus: ^7.2.2   # ou mais recente
  intl: ^0.18.1        # ou mais recente

  # NOVO PACOTE PARA FONTES
  google_fonts: ^6.2.0 # Verifique a versão mais recente em pub.dev

  cupertino_icons: ^1.0.2

  # Gerenciamento de Estado
  provider: ^6.1.1
  
  # Persistência de Dados
  shared_preferences: ^2.2.2
  sqflite: ^2.3.0
  path: ^1.8.3
  
  # Utilitários
  uuid: ^4.2.1
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  
  # Animações
  lottie: ^2.7.0
  animations: ^2.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/ # Certifique-se que esta linha existe e está correta